### ISSUE TITLE
Broken websocket support 

### ISSUE THREAD

**Issue by ogerman** [postrank-labs/goliath#228]
Em-websocket has api changes since 0.3.8
all later versions fails with 

```
[23074:ERROR] 2013-02-13 16:18:46 :: uninitialized constant EventMachine::WebSocket::HandlerFactory
/Users/ogerman/.rvm/gems/ruby-1.9.3-p327@chat/gems/goliath-1.0.1/lib/goliath/websocket.rb:77:in `response'
/Users/ogerman/.rvm/gems/ruby-1.9.3-p327@chat/gems/goliath-1.0.1/lib/goliath/api.rb:163:in `call'
/Users/ogerman/.rvm/gems/ruby-1.9.3-p327@chat/gems/goliath-1.0.1/lib/goliath/rack/async_middleware.rb:73:in `call'
/Users/ogerman/.rvm/gems/ruby-1.9.3-p327@chat/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
/Users/ogerman/.rvm/gems/ruby-1.9.3-p327@chat/gems/async-rack-0.5.1/lib/async_rack/async_callback.rb:114:in `call'
/Users/ogerman/.rvm/gems/ruby-1.9.3-p327@chat/gems/async-rack-0.5.1/lib/async_rack/async_callback.rb:91:in `block in new'
/Users/ogerman/.rvm/gems/ruby-1.9.3-p327@chat/gems/goliath-1.0.1/lib/goliath/request.rb:163:in `call'
/Users/ogerman/.rvm/gems/ruby-1.9.3-p327@chat/gems/goliath-1.0.1/lib/goliath/request.rb:163:in `block in process'
```

**Comment by paobac** [comment]
Please update the Goliath internal code so that we can use the latest em-websocket version, thank you.
