### ISSUE TITLE
Error after adding goliath to my Gemfile.

### ISSUE THREAD

**Issue by nikhilbansal** [postrank-labs/goliath#321]
Hi,
I am getting the following error after adding Goliath to my Gemfile. I am getting this error when I am trying to run my app using webrick in development mode. Please help.

Exiting
/Users/nikhilbansal/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/handler.rb:43:in `pick': Couldn't find handler for: thin, puma, webrick. (LoadError)
        from /Users/nikhilbansal/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/handler.rb:57:in `default'
        from /Users/nikhilbansal/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/server.rb:268:in `server'
        from /Users/nikhilbansal/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/commands/server.rb:112:in `print_boot_information'
        from /Users/nikhilbansal/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/commands/server.rb:64:in `start'
        from /Users/nikhilbansal/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:81:in `block in server'
        from /Users/nikhilbansal/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:76:in `tap'
        from /Users/nikhilbansal/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:76:in `server'
        from /Users/nikhilbansal/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from /Users/nikhilbansal/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:8:in `require'
        from bin/rails:8:in `<main>'

**Comment by nolman** [comment]
Are you trying to use Goliath to serve a Rails app? You will not be able to do that, Goliath is a standalone framework, while you can use `ActiveRecord` (using an event machine based adapter) and `ActiveSupport` with it, the Rails request response cycle is not supported.

**Comment by nikhilbansal** [comment]
I just want Goliath to be a part of the same codebase as of Passenger. I am still using Passenger to serve my Rails app. I am getting this error when I am trying to run passenger.

**Comment by dj2** [comment]
The rails app will load all of the gems in the bundle. So, if Goliath is in there it will be loaded by Rails. I believe you can put it in a custom group to not have it loaded in production, but not sure if that will work in dev/test.

**Comment by dankozlowski** [comment]
@nikhilbansal Are you still experiencing issues here or can we close this out?
